AWSTemplateFormatVersion: "2010-09-09"
Resources:
  HelloWorldCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: HelloWorldCluster
  HelloWorldDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions: 
        - 
          Name: "hello_world_node"
          Image: "marcohazan/hello_world_node"
          PortMappings: 
            - ContainerPort: 3000
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
      RequiresCompatibilities: 
        - FARGATE
  
      
  HelloWorldSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: HelloWorldSG
      GroupDescription: "hello world security group"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
  

  HelloWorldService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref HelloWorldCluster
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: 
            - !GetAtt HelloWorldSG.GroupId
          Subnets:
            - subnet-0d02dcb662a120421
      ServiceName: HelloWorld
      TaskDefinition: !Ref HelloWorldDefinition



